---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        exclude: |
          (^src/wao\.egg-info/)|(\.egg-info/)

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - chore
          - revert

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy

  # ---- Run pytest before push (block push on failures) ----
  - repo: local
    hooks:
      - id: pytest-pre-push
        name: pytest (pre-push)
        entry: bash -lc '.tools/run-pytest.sh'
        language: system
        pass_filenames: false
        stages: [pre-push]
  - repo: local
    hooks:
      - id: act-pre-push
        name: act (pre-push, opt-in via RUN_ACT=1)
        entry: bash -lc 'if [ "${RUN_ACT:-0}" = "1" ]; then act push --container-architecture linux/amd64 -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest; else echo "[pre-push] RUN_ACT not set -> skipping act"; fi'
        language: system
        pass_filenames: false
        stages: [pre-push]
